### ISSUE TITLE
编译后启动报错：Cannot find module 'tsconfig-paths/register'

### ISSUE THREAD

**Issue by ddzyan** [waitingsong/koid#1]
编译后启动报错，麻烦看看

2022-12-15 15:37:30,956 ERROR 72 Error: Cannot find module 'tsconfig-paths/register'
Require stack:
- /home/node_modules/@mw-components/koid/dist/configuration.js
- /home/node_modules/@mw-components/koid/dist/index.js
- /home/dist/configuration.js
- /home/node_modules/@midwayjs/core/dist/common/fileDetector.js
- /home/node_modules/@midwayjs/core/dist/service/slsFunctionService.js
- /home/node_modules/@midwayjs/core/dist/index.js
- /home/node_modules/@midwayjs/bootstrap/dist/bootstrap.js
- /home/node_modules/@midwayjs/bootstrap/dist/index.js
- /home/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/node_modules/@mw-components/koid/dist/configuration.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/node_modules/@mw-components/koid/dist/configuration.js',
    '/home/node_modules/@mw-components/koid/dist/index.js',
    '/home/dist/configuration.js',
    '/home/node_modules/@midwayjs/core/dist/common/fileDetector.js',
    '/home/node_modules/@midwayjs/core/dist/service/slsFunctionService.js',
    '/home/node_modules/@midwayjs/core/dist/index.js',
    '/home/node_modules/@midwayjs/bootstrap/dist/bootstrap.js',
    '/home/node_modules/@midwayjs/bootstrap/dist/index.js',
    '/home/bootstrap.js'
  ]
}

**Comment by waitingsong** [comment]
有没有最小复现库？

**Comment by waitingsong** [comment]
tsconfig-paths 有可能被安装到某个子目录下了
